- hosts: dbservers
  user: root
  
  roles:
   - create_oracle_groups
   - create_oracle_users
   - create_oracle_os_requirements
   - create_oracle_installation_folders
   - deploy_oracle_gold_image
